display_errors=On
display_startup_errors=On
error_reporting=E_ALL

memory_limit=512M
max_execution_time=120
max_input_time=120
post_max_size=20M
upload_max_filesize=20M

date.timezone=America/El_Salvador

cgi.fix_pathinfo=0